### ISSUE TITLE
Disable in production mode

### ISSUE THREAD

**Issue by BeeeQueue** [xoredg/apollo-link-logger#46]
It would be great if the plugin could be disabled in production easily!

Either webpack's mode, `NODE_ENV` or just a setting passed into the constructor would work, right now it's pretty cumbersome to do.

**Comment by lekoaf** [comment]
It's really not that hard to implement yourself.

```javascript
const links = [httpLink]

  if (process.env.NODE_ENV === 'development') {
    links.unshift(apolloLogger)
  }

  ApolloLink.from(links)
```

**Comment by BeeeQueue** [comment]
It's still more cumbersome than just basing it on an already existing env variable and/or a boolean passed into the constructor.
